project:
  type: website
  output-dir: docs

website:
  title: "坂本航太のブログ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts/statistics/index.qmd
        text: 記事一覧  
      

sidebar:
  -title: "記事カテゴリ"
  style: "docked"
  contents:
    - posts/statistics/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

