project:
  type: website
  output-dir: docs

website:
  title: "Kota Sakamoto"
  description: "臨床試験の実務統計家によるブログ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts/statistics/index.qmd
        text: Notes
      - href: posts/Web_tools/Web_tools.qmd
        text: Web Tools
    tools:  
      - icon: github
        href: https://github.com/kkts1010/kkts1010.github.io/
  page-navigation: true  
  page-footer:
    left :
     - text : "Kota Sakamoto"
       href : https://github.com/kkts1010/kkts1010.github.io/
    right:
     - icon : github
       href : https://github.com/kkts1010/kkts1010.github.io/
     - icon : twitter
       href : https://twitter.com/kkt_1010

execute:
  engine: knitr

format:
  html:
    mainfont: "BIZ UDPGothic"
    toc: true
    toc-depth: 2                 
    theme: cosmo
    css: styles.css
    number-sections: true
    highlight-style: ayu
    code-block-bg: true
    code-block-border-left: "#7CC4AC"
    code-overflow: scroll
    code-fold: true
    code-annotations: select
    code-copy: true            
    code-line-numbers: false    
    fig-format: svg
    fig-height: 5                   
    fig-width: 9                    
    html-math-method: katex          
    page-layout: full               
    fontsize: normal                 
    self-contained: false           
    lang: "ja"                  
    encoding: "UTF-8"
    df-print: tibble                
    toc-title: "目次"
    abstract-title: "概要"

editor: visual