---
title: "Web Tools"
---

ここでは、参考にさせていただいてるWeb URLを備忘録として保存する。

## 計量生物学会

-   [計量生物学会](https://www.biometrics.gr.jp/)
-   [統計家の行動基準](https://www.biometrics.gr.jp/news/all/standard_20150310.pdf)

## 論文雑誌

-   [Pharmaceutical Statistics](https://onlinelibrary.wiley.com/toc/15391612/current)
-   [International Journal of Epidemiology](https://academic.oup.com/ije)
-   [American Journal of Epidemiology](https://academic.oup.com/aje)
-   [Statistics in Medicine](https://onlinelibrary.wiley.com/loi/10970258)
-   [Biometrical Journal](https://onlinelibrary.wiley.com/journal/15214036)
-   [Pharmacoepidemiology ＆ Drug Safety](https://onlinelibrary.wiley.com/journal/10991557)
-   [Epidemiology](https://journals.lww.com/epidem/pages/default.aspx)
-   [Epidemiologic Methods](https://www.degruyterbrill.com/journal/key/em/html)
-   [Journal of Causal Inference](https://www.degruyterbrill.com/journal/key/jci/html)
-   [Eurpean Journal of Epidmiology](https://link.springer.com/journal/10654)
-   [Journal of Clinical Epidemiology](https://www.sciencedirect.com/journal/journal-of-clinical-epidemiology)
-   [Journal of Epideimology](https://jeaweb.jp/journal/issues/jstage/index.html)
-   [Biostatistics](https://academic.oup.com/biostatistics)
-   [The International Journal of Biostatistics](https://www.degruyterbrill.com/journal/key/ijb/html#overview)
-   [計量生物学](https://www.jstage.jst.go.jp/browse/jjb/list/-char/ja)
-   [薬剤疫学](https://www.jstage.jst.go.jp/browse/jjpe/-char/ja)
-   [すうがくぶんか株式会社](https://sugakubunka.com/)
-   [Quarto](https://quarto.org/)
-   [Git公式書籍（日本語）](https://git-scm.com/book/ja/v2)

## 医薬品開発

-   [PMDA 審査関連業務の概要について](https://www.pmda.go.jp/review-services/outline/0001.html)
-   [ICH Efficacyガイドライン](https://www.pmda.go.jp/int-activities/int-harmony/ich/0011.html)
-   [製薬協データサイエンス部会 成果物](https://www.jpma.or.jp/information/evaluation/results/allotment/results01.html#%E3%83%87%E3%83%BC%E3%82%BF%E3%82%B5%E3%82%A4%E3%82%A8%E3%83%B3%E3%82%B9)
-   [製薬協 医薬品評価委員会シンポジウム](https://www.jpma.or.jp/information/evaluation/symposium/index.html)
-   [FDA Clinical Trials Guidance Documents](https://www.fda.gov/science-research/clinical-trials-and-human-subject-protection/clinical-trials-guidance-documents)
-   [FDA Real-World Evidence Documents](https://www.fda.gov/science-research/science-and-research-special-topics/real-world-evidence)
-   [EMA Biostatistics guidelines](https://www.ema.europa.eu/en/human-regulatory-overview/research-and-development/scientific-guidelines/clinical-efficacy-safety-guidelines/biostatistics#topics)
-   [EMA Real-world evidence guidelines](https://www.ema.europa.eu/en/human-regulatory-overview/research-development/scientific-guidelines/clinical-efficacy-safety-guidelines/real-world-evidence)
-   [CDISC ADaM](https://www.cdisc.org/standards/foundational/adam)
-   [Statistical Analysi Plan(Australian Clinical Trials)](https://clinicaltrialsalliance.org.au/resource/statistical-analysis-plan/)

## 統計

-   [Pankaj Kumar Choudhary先生](https://personal.utdallas.edu/~pankaj/)
-   [Frank Harrell先生](https://www.fharrell.com/about)
-   [Bayesian Data Analysis Course](https://avehtari.github.io/BDA_course_Aalto/index.html)
-   [早稲田大学 村田先生 講義資料等](https://noboru-murata.github.io/lectures/)
-   [Camden Lopez（海外の生物統計家ブログ）](https://www.camdenlopez.com/about/)
-   [Biostatistics for Biomedical Research](https://hbiostat.org/bbrc/)
-   [久保川達也先生 書籍関連](https://sites.google.com/site/ktatsuya77/xian-dai)
-   [医学のための因果推論](https://righteous-manager-7af.notion.site/d2920bb2ebb9474bb96702d29febcb53)

## SASプログラミング

-   [SAS備忘録](https://sas-boubi.blogspot.com/2016/01/ifn-ifc4.html)
-   [Pharmaceutical Software Users Group](https://www.lexjansen.com/cgi-bin/xsl_transform.php?x=pharmasug2025)
-   [Conference Proceedings (1976 - present) ... and more](https://www.lexjansen.com/)
-   [SASユーザー会](https://www.sas.com/ja_jp/usergroups.html)
-   [SASユーザー総会 論文集アーカイブ](https://sites.google.com/view/sas-japan-user-group-archive/%E3%83%9B%E3%83%BC%E3%83%A0)
-   [SAS Forumユーザー会 2006](https://www.sas.com/offices/asiapacific/japan/usergroups/technical06/appendix.html)
-   [大阪SAS勉強会](https://sites.google.com/view/osakasasbenkyokai/%E3%83%9B%E3%83%BC%E3%83%A0)
-   [データステップ100万回　SAS新手一生](https://sas-tumesas.blogspot.com/)
-   [晴れ時々SAS](https://dengonmemo.blogspot.com/p/blog-page.html)
-   [SAS One Dash](https://sasonediver.blog.fc2.com/)
-   [我輩はブロガーではない。ネタもまだない](https://japelin.hatenablog.com/entry/2025/05/03/210416)
-   [僕の頁 <SASと臨床試験と雑談と>](http://sasboku.blog.fc2.com/blog-date-201402.html)
-   [データサイエンス100本ノック（構造化データ加工編）のSAS版](https://github.com/Nikkei-R-DataScience/sas-100knocks-preprocess/blob/main/answer/sas100knocks.ipynb)
-   [RTFファイルをPDF化するDDEプログラム](https://sasonediver.blog.fc2.com/blog-entry-342.html)
-   [SGPLOTでForest plot](https://www.docswell.com/s/6484025/54QXEY-2024-04-03-082255#p13)

## Rプログラミング（書籍）

-   [R for Data Science (2nd Edtion)](https://r4ds.hadley.nz/)
-   [Advanced R (2nd Edition)](https://adv-r.hadley.nz/)
-   [R Cookbook, 2nd Edition](https://rc2e.com/)
-   [Quarto 公式guide](https://quarto.org/docs/guide/)

## Rプログラミング（海外サイト）

-   [Tidyverse style guide](https://style.tidyverse.org/index.html)
-   [R Workflow for Reproducible Data Analysis and Reporting](https://hbiostat.org/rflow/)
-   [Building reproducible analytical pipelines with R](https://raps-with-r.dev/)
-   [R Rpharma](https://rinpharma.com/)
-   [R Workflow（Frank Harrell先生](https://www.fharrell.com/post/rflow/)
-   [Reproducible Medical Research with R](https://rmrwr.netlify.app/)
-   [R for Clinical Study Reports and Submission](https://r4csr.org/)
-   [An Introduction to Statistical Programming Methods with R](https://smac-group.github.io/ds/)
-   [Tables in Clinical Trials with R](https://rconsortium.github.io/rtrs-wg/)
-   [Introduction to tern](https://cran.r-project.org/web/packages/tern/vignettes/tern.html)
-   [Workshops at rstudio::conf 2022](https://github.com/rstudio-conf-2022)
-   [TLG Catalog](https://insightsengineering.github.io/tlg-catalog/stable/)
-   [Introduction to {rtables}](https://insightsengineering.github.io/rtables/v0.6.10/articles/rtables.html)
-   [Reproducible Environments(Posit社)](https://solutions.posit.co/envs-pkgs/environments/)
-   [R Submission Pilot 1](https://rconsortium.github.io/submissions-pilot1/index.html)
-   [R Submission Pilot 3](https://rconsortium.github.io/submissions-pilot3-adam/main/index.html)

## Rプログラミング（日本語）

-   [データサイエンス100本ノック（構造化データ加工編）をRで解く](https://zenn.dev/masayukeeeee/articles/a7fbdb6f2f38b9)
-   [Rによる再現可能なデータ分析（瓜生真也先生）](https://uribo.github.io/rrr/)
-   [Rによるデータ解析のための前処理（瓜生真也先生）](https://uribo.github.io/dmr/)
-   [次の一歩を踏み出すためのtidyverse入門（瓜生真也先生）](https://uribo.github.io/230827ism_ws/)
-   [今日からできる再現可能な論文執筆（国里愛彦先生・竹林由武先生）](https://ykunisato.github.io/jpa2020-tws-002/)
-   [はじめよう！R（小杉考司先生）](https://kosugitti.github.io/slides/TokyoR117/RforBeginner.html#r%E3%82%92%E3%81%95%E3%82%8F%E3%81%A3%E3%81%A6%E3%81%BF%E3%81%BE%E3%81%97%E3%82%87%E3%81%86)
-   [気軽にRでWebサイト](https://shohei-doi.github.io/academic-website/get-started.html)
-   [Rではじめようモダンなデータ分析](https://book.mynavi.jp/manatee/series/detail/id=54225)
-   [私たちのR](https://www.jaysong.net/RBook/)
-   [Rプログラムの個人ブログ](https://t-arae.blog/)
-   [データハンドリング入門](https://kazutan.github.io/kazutanR/hands_on_170730/index.html)
-   [2025年4月2日 ワークショップ「オープンソースソフトウェア「R」の承認申請業務での利用実態と今後の展望について」](https://www.jpma.or.jp/information/evaluation/symposium/DS_202504_01sympo.html)
-   [dplyrを使いこなす！Window関数編](https://qiita.com/matsuou1/items/db6e8c48fcfd791dd876)
-   [R Markdownで数式を使ったPDFを作成するときのメモ](https://www.anarchive-beta.com/entry/2019/08/10/211122)

## 研究関連

-   [Writing-Tips Series(Journal of Clinical Epidemiology)](https://www.jclinepi.com/content/jce-Writing-Tips-Series)

## 論文

-   [Ten Simple Rules for Reproducible Computational Research](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285)
-   [山本先生_LatexによるBibTeXにおけるbibファイルの書き方](https://mathlandscape.com/latex-bib/)

## ブログ関係

-   [長島健悟先生のブログ](https://nshi.jp/)
-   [KRSK先生のブログ](https://www.krsk-phs.com/)
-   [司馬先生のブログ](https://162348.github.io/)
-   [Yanagimoto先生のブログ](https://zenn.dev/nicetak)
-   [すきとほるさんのブログ](https://nothing-without-poison.com/)

## Quartoブログ

-   [tutorial](https://ivelasq.quarto.pub/building-a-blog-with-quarto/intro.html)
-   [Building a blog with Quarto](https://qiita.com/Qiita/items/c686397e4a0f4f11683d)
-   [Markdown記法チート](https://qiita.com/Qiita/items/c686397e4a0f4f11683d)
-   [Quartoでアカデミックなスライドを作るためのTips](https://zenn.dev/nicetak/articles/quarto-tips-2022)

## Tips

-   [Excelシートの一括変換 note](https://note.com/office_haru/n/n35ab7211eece)
-   [ExcelファイルをまとめてPDFファイルに変換したい](https://zenn.dev/takaha4k/articles/a0980bea89b883)
-   [複数のExcelファイルを一括でPDFファイルに変換する方法](https://kouritsukafiles.com/convert-excelfiles-to-pdf/)
-   [メモ帳だけで作成！複数のExcelファイルをPDFに一括変換](https://skainoblog.com/pdftoexcel/)
-   [WinMerge日本語版](https://winmergejp.bitbucket.io/)

## その他

-   [熊本大学大学教育統括管理運営機構附属数理科学総合教育センター](https://www.sci.kumamoto-u.ac.jp/math/exercise.html)