---
title: "大人の英語学習勉強1"
author: "坂本航太"
categories: [English]
date-modified: "2025-07-23"
abstract-title: Abstract
abstract: ""
date: "2025-07-23"
---

# 背景

本業がある社会人こそ、英文法を利用することで効率良く英語を使えるようになります。交渉での細かいニュアンスには、「時制・助動詞」の力が絶対に必要になりますし、複雑な説明をするときには「比較・関係詞」を駆使することになります。英文法が崩れたプレゼンテーションはもやは聞いてもらえないでしょう。

「大人の会話」であるだけに、中学英文法では足りず、高校レベルまでの英文法の全範囲が必須となります。何より、きちんとした英文法を使うことは、ビジネスにおいての「信用」につながります！

私にとっては、研究者としての立場もあり、論文投稿に加えて、「論文を読む」という動作において、正しく著者の考えを理解するために、「英文法」は必須です。基礎を固めておきましょう。

ここでは、高校英文法をひとつひとつ分かりやすく。という本を基に勉強していく！

# 目次

1.  基本文系

    1.  SVの文

    2.  SVCの文

    3.  SVOの文

    4.  SVOOの文

    5.  SVOCの文

2.  時制

    1.  現在形

    2.  過去形

    3.  未来を表す表現

    4.  現在完了形

    5.  過去形と現在完了形の違い

    6.  過去完了形

    7.  未来完了形

    8.  現在進行形

    9.  過去進行形・未来進行形

    10. 現在完了進行形

    11. 過去完了進行形

3.  受動態

    1.  受動態

    2.  SVOOの受動態

    3.  SVOCの受動態

    4.  進行形と完了形の受動態

4.  助動詞

    1.  助動詞

    2.  助動詞のもう一つの意味

    3.  助動詞のいろいろな表現

5.  準動詞

    1.  不定詞とは

    2.  不定詞の意味上の主語

    3.  SVO＋不定詞、SVO＋原型不定詞

    4.  不定詞のいろいろなかたち

        1.  否定形、進行形、独立不定詞

    5.  不定詞のいろいろなかたち

        1.  完了不定詞、不定詞の受動態

    6.  動名詞

    7.  不定詞と動名詞のちがい

    8.  分詞

    9.  補語になる分詞

    10. 分詞構文

    11. 分詞構文のいろいろなかたち

        1.  完了形の分子構文、接続詞＋分詞構文

    12. 独立分詞構文と慣用表現

        1.  独立分詞構文とwith＋名詞＋分詞

6.  仮定法

    1.  仮定法過去

    2.  仮定法過去完了、仮定法過去と仮定法過去完了のミックス形

    3.  仮定法の重要表現

        1.  未来の仮定法、仮定法の慣用表現

    4.  仮定法の重要表現

        1.  未来の仮定法、仮定法の慣用表現

7.  比較

    1.  原級を使った表現

    2.  比較級を使った表現

    3.  最上級を使った表現

8.  関係詞

    1.  関係代名詞の用法

        1.  関係代名詞の基本、主格の関係代名詞

        2.  目的格の関係代名詞、所有格の関係代名詞

        3.  そのほかの関係代名詞

            1.  関係代名詞that、関係代名詞what

        4.  関係代名詞の注意すべき用法

            1.  前置詞＋関係代名詞

        5.  関係副詞の用法

        6.  関係代名詞と関係副詞の違い

        7.  カンマ付きの関係代名詞と関係副詞

            1.  関係代名詞、関係副詞の非制限用法

        8.  複合関係詞の用法

9.  その他の重要な文法

    1.  名詞のカタマリをつくる接続詞

    2.  副詞のカタマリをつくる接続詞

    3.  強調構文とは

    4.  形式主語・形式目的語を使った文

    5.  時制の一致と話法

    6.  疑問詞を使った重要表現

## 関先生の真英文法の目次

1.  時制

    1.  現在形と過去形

    2.  時制の細かい用法

    3.  進行形

2.  時制

    1.  現在完了形

    2.  過去完了形

    3.  未来完了形（will have p.p.）

    4.  現在完了形の応用

3.  接続詞

    1.  等位接続詞（and型）

    2.  従属接続詞（when/if型）

    3.  名詞節もつくる従属接続詞

    4.  時・条件を表す副詞節内での「現在形の特別用法」

4.  仮定法

    1.  仮定法の公式

    2.  公式通りではない仮定法

    3.  仮定法の「慣用表現」

5.  助動詞

    1.  基本助動詞の詳説

    2.  助動詞の過去形

    3.  mayの慣用表現、shouldの特別用法

    4.  その他の助動詞と助動詞相当表現

    5.  助動詞 vs 代表表現

    6.  助動詞＋have p.p.

6.  冠詞

    1.  定冠詞 the

    2.  不定冠詞 a

7.  名詞

    1.  可算名詞

    2.  不可算名詞

    3.  可算・不可算の感覚を磨く

    4.  「集合」という感覚を持つ名詞

8.  代名詞

    1.  人称代名詞

    2.  it/one/otherなど

    3.  その他の代名詞

9.  形容詞

    1.  形容詞の用法

    2.  「意味の識別」が問われる形容詞

10. 副詞

    1.  副詞という「品詞」の意識

    2.  「位置」が狙われる副詞

    3.  「まぎらわしい副詞」の判別

    4.  「場所・時間の副詞」に関する副詞の特別用法

11. 文型

    1.  動詞の詳述

    2.  第1・2・3文型

    3.  第4文型

    4.  第5文型

12. 不定詞

    1.  不定詞の基本3用法

    2.  不定詞の様々な形

    3.  不定詞を使った慣用表現

    4.  toが持つ「未来志向性」

13. 動名詞

    1.  動名詞の基本

    2.  目的語にくる"to" vs "ing"

    3.  動名詞の慣用表現

14. 

## 英語の基本ルール

英語の文章を作るパーツ

-