---
title: "医学論文を書くための心構え"
author: "坂本航太"
categories: [医学論文]
date-modified: "2025-08-24"
abstract-title: Abstract
abstract: ""
date: "2025-08-24"
---

## なぜ論文を書くのか？

## 書かなければ何も残らない。

## 英語で論文を書こう

## 「書く」ことを意識して「読む」

論文を書くには、様々な準備が必要がある。その第一歩が、常日頃から英語論文を読むことである。**「忙しいから論文を読む暇がない」は禁句である。まともに論文を書ける医師は決してそんなセリフを吐かない。1日15分でもいいから論文を読む習慣は必要である。**

　論文を読むことは、ランニングと同じである。はじめは走ることが苦手でも、毎日走れば、そのうち苦になくなる。ただし、漠然と英語論文を読み続けても、英語論文を書けるようにはならない。AbstractとTableとFigureをConclusionだけ読めば論文の大筋はつかめる。しかし、そのような「ななめ読み」を続けては、臨床研究能力はいつまでたっても身に付かないし、英語論文を書くこともおぼつかない。

　自ら筆を執り英語論文を書くことを強く意識して、日ごろから論文を精読することが推奨される。10本の論文のabstractを読み飛ばすよりも、1本の論文を隅から隅まで精読する方が、臨床研究能力、論文執筆力向上にとって有用である。

IMRAD(Intoroduction,Methods,Results and Discussion）の順番に沿って、論理展開を追いながら読むことが、英語力・論理力だけでなく論文執筆力への近道である。

自分の専門分野における主要なjournalは毎号チェックしよう。さらに、pubmedで検索し、良い論文を厳選して読むようにしよう。ただし、検索そのものに時間をかけないことが肝心である。膨大な論文を検索しそれを整理することに時間と労力を費やし、検索した論文の精読を怠っている研究者が少なくない。限られた時間はなるべく論文を読むことに費やすべきである。

英語論文を精読する際、知らない単語を調べる必要が生じたら、英英辞典を使うことを推奨する。

日本人が医学英語論文を書くための効率的な方法として、自分の専門領域の論文に頻出する表現のリストを作成することをお勧めする。常日頃から英語論文を読んで、よく使われている表現、使える構文やパラグラフをリストアップしておこう。論文の各節（Introduction, Methods, Results , Discussion , Conclusion ,Acknowledgement）ごとに頻出表現をまとめておくとよい。

これによって、自分が使える英語表現のストックを増やしていくのである。自分で英語論文を書くとき、自作の頻出表現リストから、文中にふさわしい表現を当てはめて書くようにしよう

## いつ論文を書き始めるか？

## 論文執筆時間の短縮