---
title: "Abstractの書き方"
author: "坂本航太"
categories: [医学論文]
date-modified: "2025-10-13"
abstract-title: Abstract
abstract: ""
date: "2025-10-13"
---

-   Abstractの鉄則

    -   ㉛「complete, accurate and clear」を追求する。

    -   ㉜キモとなる統計分析結果を厳選して示す。

    -   ㉝可能な限り、相対リスクだけでなく絶対リスクも示す。

    -   ㉞AbstractのConclusionに論文のすべてを凝縮する。

-   Abstractの鉄則

    -   投稿論文が査読(review)に回るかどうかは、Abstractの良し悪しにかかっている。BMJの投稿規定に、以下のように明記されている。

        -   We may screen original research articles by reading only the abstract.

    -   実際、一流誌のeditor's kickは早い。たった一人のeditorがTitleとAbstractを読んだだけで迅速に足切りの決断を下す。足切りを伝えるメールは、一週間以内、ときには数日で送られてくる。

    -   BMJの投稿規定に、Abstractを書く上での鉄則が明示されている。

        -   Please ensure that the structured abstract is as complete, accurate, and clear as possible -but not unnecessarilly long.

    -   Authoerが絶対に避けるべきは、せっかくの本文の内容が悪くないにもかかわらず、Abstractがまずいせいで、外部査読に回る機会を失ってしまうことである。

    -   まず本文を完成させたうえで、Abstractを作成すべきである。

    -   論文の各パーツを書く順番は、Introduction→Methods→Results→Discussion→Abstract→Titleとするのが正しい。

    -   Abstractはmain text全体をdistilしたものである。Abstractだけ読んで全体像が分かるように書かなければならない。

    -   本文からkey sentenceをいくつか抜いてきて、それらをコピー・ペーストしてつなぎ合わせているAbstractを見かけることが多い。そのようなAbstractは、reviewerにも読者にもあまり良い印象を与えない。適切に言い換えるようにしたい。

    -   Abstractの5個程度のkey wordsはMeshタームとすべきである。

-   Abstractの各パーツの内容

    -   標準型：4パーツ

        -   Background,

        -   Methods

        -   Results

        -   Conclusion

    -   BMJ型：8パーツ

        -   Objectives

        -   Design

        -   Setting

        -   Participants

        -   Intervention or Exposure

        -   Main outcome measures

        -   Resutls

        -   Conclusion

    -   JAMA型：10パーツ

        -   Importance

            -   The abstract should begin with a sentence or 2 explaining the clinical (or other) importance of the study question.

        -   Objective

            -   State the precise objective or study question addressed in the report (eg, "To determine whether..."). If more than 1 objective is addressed, the main objective should be indicated and only key secondary objectives stated. If an a priori hypothesis was tested, it should be stated.

        -   Design

            -   Describe the basic design of the study and include the specific study type (eg, randomized clinical trial, cohort, cross-sectional, case-control, case series, survey, meta-analysis, bibliometric analysis). State the years of the study and the duration of follow-up. For older studies (eg, those completed \>3 years ago), add the date of the analysis being reported. If applicable, include the name of the study (eg, the Framingham Heart Study). As relevant, indicate whether observers were blinded to patient groupings, particularly for subjective measurements.

        -   Setting

            -   Describe the study setting to assist readers to determine the applicability of the report to other circumstances, for example, multicenter, population-based, primary care or referral center(s), etc.

        -   Participants

            -   State the clinical disorders, important eligibility criteria, and key sociodemographic features of patients (or other study participants). The numbers of eligible participants and how they were selected should be provided, including the number approached but who refused or were excluded. For selection procedures, these terms should be used, if appropriate: random sample (where random refers to a formal, randomized selection in which all eligible individuals have a fixed and usually equal chance of selection); population-based sample; referred sample; consecutive sample; volunteer sample; convenience sample. If matching is used for comparison groups, characteristics that are matched should be specified. In follow-up studies, the proportion of participants who completed the study must be indicated.

        -   Interventions for clinical trials or Exposures for observational studies

            -   The essential features of any interventions, or exposures, should be described, including their method and duration. The intervention, or exposure, should be named by its most common clinical name, and nonproprietary drug names should be used.

        -   Main Outcomes and Measures

            -   Indicate the primary study outcome measurement(s) as planned before data collection began. If the manuscript does not report the main planned outcomes of a study, this fact should be stated and the reason indicated. State clearly if the hypothesis being tested was formulated during or after data collection. Explain outcomes or measurements unfamiliar to a general medical readership.

        -   Results

            -   Summary demographic information (eg, characteristics such as sex and age) and the number of study participants should be reported in the first sentence of the Results paragraph. The main outcomes of the study should be reported and quantified, including final included/analyzed sample. When possible, present numerical results (eg, absolute numbers and/or rates) with appropriate indicators of uncertainty, such as confidence intervals. Include absolute numbers and/or rates with any ratio measures and avoid redundant reporting of relative data (eg, % increase or decrease). Use means and standard deviations (SDs) for normally distributed data and medians and ranges or interquartile ranges (IQRs) for data that are not normally distributed. Avoid solely reporting the results of statistical hypothesis testing, such as *P* values, which fail to convey important quantitative information. For most studies, *P* values should follow the reporting of comparisons of absolute numbers or rates and measures of uncertainty (eg, 0.8%, 95% CI −0.2% to 1.8%; *P* =.13). *P* values should never be presented alone without the data that are being compared. See also [Reporting Standards and Data Presentation](https://jamanetwork.com/journals/jama/pages/instructions-for-authors#SecReportingStandardsandDataPresentation). Measures of relative risk also may be reported (eg, relative risk, hazard ratios) and should include confidence intervals. Studies of screening and diagnostic tests should report sensitivity, specificity, and likelihood ratio. If predictive value or accuracy is reported, prevalence or pretest likelihood should be given as well. All randomized clinical trials should include the results of intention-to-treat analysis as well. In intervention studies, the number of patients withdrawn because of adverse effects should be given. Approaches such as number needed to treat to achieve a unit of benefit may be included when appropriate. All surveys should include response/participation rates.

        -   Conclusion and Relevance

            -   Provide only conclusions of the study that are directly supported by the results. Give equal emphasis to positive and negative findings of equal scientific merit. Also, provide a statement of relevance indicating implications for clinical practice or health policy, avoiding speculation and overgeneralization. The relevance statement may also indicate whether additional study is required before the information should be used in clinical settings.

    -   標準型の場合、Backgroundは2文、Methodsは3～4文、Resultsは3～4文、Conclustionは2文、あわせて10～12文が、バランスの良い構成である。1文を20\~25 words程度に収めれば、全体を200～300 wordsに仕上げることができる。