---
title: "Methodsの書き方"
author: "坂本航太"
categories: [医学論文]
date-modified: "2025-10-13"
abstract-title: Abstract
abstract: ""
date: "2025-10-13"
---

-   Resultsの鉄則

    -   ⑲Resultsには一切の価値判断を交えず、事実を客観的に淡々と書く。

    -   ⑳Methodsの順に沿って実験・観察結果を簡潔明瞭に書く。

    -   ㉑TableとFigureをself-explanatoryにする。

    -   ㉒Table・FIgureと本文の重複記載を避ける。

    -   ㉓Resultsにおける定型表現を用いたfool-proof Englishに徹する。

## Results

ICMJEの和訳：<https://www.honyakucenter.jp/usefulinfo/uniform-requirements/>

::: callout-note
###### **e. 結果**

研究結果は、本文および図表で論理的に順を追って提示し、はじめに主要な、または最も重要な所見を述べるようにする。図表中のデータをすべて本文で繰り返すことはせず、最も重要な知見のみを強調また要約する。「方法」セクションで示したすべての主要評価項目および副次評価項目について、データを提供する。追加資料／補助的資料および技術的詳細については、本文の流れを損なうことなく必要に応じて参照できるよう付録［appendix］に収めてもよく、また雑誌の電子版のみに掲載することもできる。

解析結果は、算出値（たとえばパーセンテージなど）のみではなく、算出に用いられた絶対数も記載する。図表の使用は、論文の論点の説明および裏付けデータの評価に必要なものに限定する。項目が多い場合には表の代わりにグラフを用いるが、グラフと表でデータを重複させてはならない。｢ランダム｣［random］（無作為化の手法を示唆する）、｢正規｣［normal］、｢有意｣［significant］、｢相関｣［correlations］、｢標本｣［sample］などの統計専門用語を非専門的な文脈で用いることは避ける。

年齢や性別などの人口統計学的変数による報告データの分割は、研究間でサブグループのデータ併合を容易にすることから、階層化を妨げるやむを得ない理由がない限り、所定の手順として行うべきである。階層化が不可能な場合は、その理由を説明する必要がある。

###### **f. 考察**

考察では、まず主要な所見を簡潔に要約した後、それらの所見について考えられる機序や説明を論じていくとよい。その研究のどこが新しく、重要かを強調し、関連するエビデンス全体に照らして研究所見を論じる。この研究の限界について述べ、その研究所見が、将来の研究および臨床現場や臨床方針にもたらす影響について検討する。また適切な場合は、性別／ジェンダーなどの変数が研究所見に及ぼす影響や所見との関連性について考察し、データの限界について論じる。「緒言／序論」や「結果」のセクションなど、原稿の他の部分で述べたデータやその他の情報については、詳細を繰り返さない。

結論は研究目標と関連付けて述べ、制限を設けない言明やデータによる十分な裏付けのない結論は避ける。特に、臨床的な意義と統計的有意性は明確に区別し、原稿に経済面についての適切なデータや解析が含まれていない限り、経済的利益や費用について言及することは避ける。まだ終了していない研究について優先権を主張したり、そのような研究の存在をほのめかしたりすることは避ける。妥当性がある場合は新しい仮説を述べ、仮説であることを明記すること。

###### **g. 参考文献**

**i. 一般的注意事項**

著者は、直接参考文献にはできるだけ原著論文を提示すべきである。参考文献は、できるだけ抄録ではなく既刊の論文とする。著者、編集者、または査読者は、個人的な利益のために参考文献を利用してはならない。著者は、ハゲタカジャーナル／偽物ジャーナルから論文を引用することは避けるべきである。プレプリントを引用する場合は、引用の参照元がプレプリントであることを明示すべきである（セクションIII.D.3も参照）。総説［review article］の参照は、多数の文献を読者に紹介する効率的な方法とはなり得るが、総説は必ずしも原著論文を正確に反映しているわけではない。その一方で、ある話題に関する原著論文の参照リストが膨大になると、紙面をとりすぎることがある。特に現在では、掲載論文の電子版に参考文献を追加することが可能であり、読者は電子的な文献検索によって公表論文を効率的に検索できるため、文献数が少なくても主要な原著論文を押さえていれば、より網羅的なリストと同等の役割を果たすことが多い。

採用されたがまだ掲載されていない論文を参考文献とする場合は、｢掲載準備中｣［in press］または｢出版予定｣［forthcoming］と表示すべきである。 投稿後まだ採用されていない原稿の情報を引用する場合は、その情報提供者から書面で承諾を得た上で、本文中に｢未発表知見｣［unpublished observation］と明記して引用する。

掲載論文では、使用したデータセットを、永続的な一意の識別子を用いて参照しなければならない。

公開情報源からは得られない重要情報を提供するものでない限り、｢私信｣［personal communication］の引用は避ける。私信を引用する場合は、本文中に括弧書きで相手の氏名および情報入手日を明記する。科学論文に引用するためには、私信の提供者から使用許可およびその情報が正確であるという確認を書面で得なければならない。

AIによって作成された資料を一次資料として参照することは認められない。

雑誌発行元は、参考文献の引用の正確性をすべて点検しているわけではない。そのため、掲載後の論文に引用文献の誤りが見受けられることもある。このような誤りを最小限にするために、PubMedなどの電子的文献データベースを用いて、あるいは原本の印刷物と照らし合わせて、引用文献を検証しておく必要がある。また著者には、文脈中で撤回について言及する論文を除き、撤回された論文が引用されていないかどうか点検する責任がある。MEDLINEに索引登録されている雑誌の掲載論文については、ICMJEはPubMedを論文の撤回に関する確かな情報源と考えている。MEDLINEでは、撤回された論文は「Retracted publication［pt］」（［pt］は出版のタイプを示す）を検索語としてPubMedを検索するか、PubMedの撤回論文リスト（ncbi.retracted-publication \[pt\]）を直接調べることにより特定できる。

参考文献には、本文で最初に言及された順番に通し番号を振る。本文、表、および図の説明文では、括弧書きのアラビア数字で参考文献を識別する。

表や図の説明文のみで引用された参考文献については、その図表が本文中で最初に言及された順番に従って番号を振る。雑誌名は、MEDLINEで用いられているスタイルに従って略記する（www.ncbi.nlm.nih.gov/nlmcatalog/journals）。電子的情報（インターネット情報）については、本文中に括弧書きで引用元を示すよう求める雑誌もあれば、付番した参考文献として本文の後に置く雑誌もある。著者は、この点について、投稿を予定している雑誌の発行元と協議する必要がある。

**ii. スタイルおよび形式**

参考文献は、NLMの「参考文献のサンプル」（www.nlm.nih.gov/bsd/uniform_requirements.html）のウェブページに要約され、NLMのCiting Medicine第2版（www.ncbi.nlm.nih.gov/books/NBK7256/）に詳述されている基準に従って記載する必要がある。これらの情報源は新しい媒体の開発に伴って定期的に更新されており、最新版には印刷文書、未発表資料、視聴覚媒体、CD-ROM、DVDまたはディスクに保存された資料、ならびにインターネット上の資料に関するガイダンスが含まれている。

###### **h. 表**

表は情報を簡潔に記録し、効率的に表示するものであり、また必要な程度に詳細かつ精密な情報を提供する。データを本文ではなく表に示すことで、本文の長さを短縮できることが多い。

表は各雑誌の要件に従って作成する。誤りを避けるため、雑誌が採用している出版用ソフトウェアに表を直接インポートすることができればそれが最善である。表には本文で最初に引用された順番に従って通し番号を振り、各表にタイトルを付ける。表のタイトルは簡潔かつ自明でなければならず、読者がわざわざ本文に戻って確認しなくても表の内容を理解できるような情報を含める。各表が必ず本文中で引用されていることを確かめる。

表の各列には、手短な、または略語による見出しを付ける。説明的な内容は、見出しではなく脚注に記載すべきである。一般的でない略語はすべて脚注で説明し、情報の説明に必要であれば記号を用いる。使用する記号は雑誌によって異なる場合があるため（アルファベットや、\*、†、‡、§などの記号）、従うべき慣行について各雑誌の投稿規定を確認する。標準偏差や標本平均の標準誤差など、変動の統計的尺度に何を用いたかを明記する。

既発表または未発表の他の情報源から得たデータを用いる場合は、許可を得た上で出典に対し十分な謝辞を述べる。

印刷版に掲載するには情報量が多すぎる実証データを収載した表を追加する場合、その雑誌の電子版に掲載するのが適切な場合もあり、また記録保管サービス［archival service］での保管や、読者が著者本人から直接入手できるようにすることも可能である。このような追加情報が入手可能であることやその入手先については、読者に対し本文中で適切に補足する必要がある。検討対象となるこれらの表も投稿論文とともに提出し、査読者の閲覧に供する。

**i. 図版（図）**

図版のデジタル画像は、印刷出版に適した形式で提出する。大半の投稿システムでは、画像の質について細かい規定を設けており、原稿のアップロード後にチェックを行っている。印刷したものを提出する場合、専門家レベルの描画を撮影したものか、写真画質のデジタルプリントを提出する。

放射線画像やその他の臨床および診断画像、病理標本の写真、顕微鏡写真については、高解像度の写真画像ファイルを送付する。事前画像と事後画像は、同一の濃度（明暗）、方向、および照明色で撮影すべきである。多くの科学論文ではブロット［blots］が主要なエビデンスとして用いられることから、ブロット写真の原図を雑誌のウェブサイトに保存するよう編集者が求める場合もある。

図を作り直す雑誌もあるが、多くの雑誌では行っていない。そのため、図中の文字、数字、記号は明瞭かつ全体で統一させたものとし、掲載のために図が縮小されても十分に判読できる大きさとする必要がある。図はその多くが将来そのままスライド発表で使用されるため、できる限りひと目で内容がわかるようにする。タイトルや詳細な説明は図版の説明文に記載し、図版そのものには記入しない。

顕微鏡写真には縮尺目盛を入れる。顕微鏡写真で使用する記号、矢印、文字は背景に対して目立たせる。顕微鏡写真に入れた目盛について説明し、染色方法を明らかにする。

図には本文で引用された順番に従って通し番号を振る。図がすでに公表されたものである場合は、原図の出典に対して謝辞を述べ、著作権所有者から得た複製許可の書面を提出する。パブリック・ドメインの文書を除き、著作者や発行元の如何を問わず、許可を得る必要がある。

図の説明文は、それぞれの図版に対応するアラビア数字を添えて原稿の別ページに配置する。図版の一部分を特定するために記号、矢印、番号、または文字を使用した場合は、説明文中でそれぞれ何を示すかを明確に述べ、説明を加える。

###### **j. 測定単位**

長さ、高さ、重量、容積の測定値はメートル法単位（メートル、キログラム、リットル）またはその10の整数乗倍で報告する。

温度は摂氏温度（°C）で表記する。血圧は、雑誌側から特に他の単位が指定されていない限り、水銀柱ミリメートル（mm Hg）で表記する。

血液検査値、生化学検査値、その他の測定値の報告に用いる単位は雑誌によって異なる。著者は必ず雑誌ごとにその投稿規定を参照し、検査についての情報を現地で使用されている単位系と国際単位系［International System of Units: SI］の両方で報告すべきである。

SI単位は万国共通で用いられているわけではないため、編集者は著者に対し、代替単位またはSI以外の単位を加えるよう求めることがある。薬物濃度はSI単位または質量濃度のいずれかで報告することができるが、別の単位が適切な場合は括弧書きで表示する。

###### **k. 略語と記号**

標準的な略語のみを用いる。標準的でない略語を使用すると、読者が混乱する可能性がある。原稿のタイトルでは略語の使用を避ける。標準的な測定単位の略語以外は、初出時にスペルアウトし、その後ろに続けて略語を括弧書きで記載する。
:::

## Resultsに書くべき項目

1.  介入研究のResults

2.  観察研究のResults

    (1)：適格基準に沿った対象者の選択過程

    ・研究の各段階における人数

    ・各段階での非参加者の除外・辞退理由

    ・参加者の特徴・潜在的交絡因子に関する記述統計

    ・それぞれの変数について、データが欠測した参加者数

    (2)：分析結果

    ・アウトカムの発生数と割合

    ・調整前の推定値と交絡因子での調整後の推定値、そしてそれらの95%信頼区間

    ・サブグループ解析など、実施したほかの解析の結果

## データの記述法

1.  割合・代表値の記述

    本文中やTable中に割合を表記するときは、分母と分子両方の数値を記述する。同じ20%でも20/100と1/5では意義が異なる。分母が10以下の場合は、%表示に意味はない。

    正規分布している連続変数は、Mean±SDではなく、Mean（SD）という表記が推奨される。平均値の標準誤差（SE）はデータの分布ではなく、推測統計の指標である。

    正規分布でない場合は、中央値と四分位範囲（IQR）を表記する。IQRは25パーセンタイル値と75パーセンタイル値を下限・上限とする範囲

2.  P値の記述

    P値は具体的な数値を記述する。P値が0.01を上回る場合、有効数字第2位まで示す。

3.  回帰分析結果の記述

    統計解析ソフトによる回帰分析の出力結果をそのまま論文原稿にコピー＆ペースト刷るのは絶対やめよう。

    AbstractやResultsの本文中に記載する際、回帰係数・95%信頼区間・P値のどれかを省くとすれば、P値を省くべきである。

    例えば、OR, 0.87:95%CI, 0.78-0.97

    1.  Table,Figureの作成

        ①Self-explanatoryの原則

        Table/Figureの一つひとつはself-explanatoryでなければならない。Table/Figureの内容を理解するためにいちいち本文に戻らなくてはならないような書き方は避けなければならない。Table/Figureのキャプションに、そのTable/Figureを理解するための簡潔な説明を書いてもよい。略語(abbreviation）のフル・スペルもTable/Figureごとに記載が必要である。

        ②重複記載の制限

        本文とTable/Figureとのデータの完全重複は、論文執筆初心者が陥りやすい誤りの一つである。カギとなる結果（key results）は重複してもよい。しかし、本文にTable/Figureの説明をだらだらと記述してはならない。本文には、key resultsのほかに、Table/Figure中のデータの傾向のみを記載する。

        ③Table/Figureの数・量の制限

        多くのjournalでは、掲載できるTable/Figureの総数を制限している。特に強調したい点のみTable/Figureに示す。

        相対的に重要でない結果は本文のみ簡潔に示すべきである。もしくは、Appendix Table/FigureがOKならば、重要でない結果は、supplementary materialにまとめ、本文にはその傾向だけを簡潔に示すという手段もある。

## Resultsの表現技術

1.  Resultsの書き方における注意点

    ①過去形、能動態で書く。

    Resultsはすべて過去形で書くことが原則である。また、能動態で書くことが推奨される。

    ②Methodsで説明していないことをResultsに書いてはならない。

    MethodsとResultsの関係は1:1対応でなければならない。

    Methodsに書かれている順番に、対応するResultsが書かれている必要がある。Methodsに書かれていないResultsを書いてはならない。また、Methodsに書いてあるのに、対応するResultsが書かれていないのも不適切である。

    ③研究目的と直接関連しない結果を書いてはならない。

    その通り。

    ④Resultsの中に価値判断めいた表現を用いてはならない。

    Resultsには観察や実験の結果を淡々と記述する。Resultsに対する解釈や価値判断の一切は、Discussionに書くべきである。

    Resultsでは群間の比較を統計的に検定した結果を書くべきである。原則として、形容詞は比較級だけを用い、原級を用いてはならない。**比較を伴わない絶対評価をResultsに記載することは不可である。**

    -   **悪い例（原級・絶対評価）:**

        -   「A群の血圧は**高かった** (high)。」

        -   **なぜダメか？**：「高い」はあなたの**主観的な評価**です。「何と比べて？」が曖昧です。正常値と比べて高いのか、あなたの期待より高いのか、読者には分かりません。これは「解釈」であり、Discussionで書くべきことです。

    -   **良い例（比較級・相対比較）:**

        -   「A群の血圧は、B群に比べて**有意に高かった** (significantly higher) (p \< 0.05)。」

        -   **なぜ良いか？**：これは「AとBを比べた」という**客観的な事実**を述べているだけです。あなたの感想や評価は入っていません。

    ⑤統計用語と紛らわしい単語を用いない。

2.  Resultsにおける定型表現

    Resultsに示される表現は、定型句のオンパレードと言ってよい。論文執筆初心者は、定型表現を用いたfool-proof Englishの表現に徹するべきである。以下は例。

    ①並列

    以下の二文は完全に同義である。

    ・Inhospital mortality was X% in treatment A, Y % in treatment B, and Z% in Treatment C.

    ・Inhospital mortality was X%, Y% and Z% in treatments A, B and C, respectively.

    ②比較

    ・The proportion of complications was significantly lower in Group A than Group B.

    ・The proportion of complications in Group A was significantly lower than that in Group B.

    ・Group A had a significantly lower proportion of complications than Group B.

    ・Patients in Group A were significantly less likely to have complications compared with those in Group B.

    ・Patients in Group A were at significantly lower risk of complications relative to those in Group B.

    ③増減

    ・Table 2 shows a significant reduction in salt intake between 1970 and 2000.

    ④関連

    ・Older age was significantly associated with higher mortality.

    ・There was a linear association between older age and higher mortality.

    ⑤有意差がない場合の表現

    ・The chi-square test showed no significant difference in the proportions of complication between Group A and Group B (12.4 % vs. 10.1 % , P=010).

    ・The difference in complication between Group A and B did not reach statistical significance(12.4% vs 10.1%, P =0.10).

    ⑥多変量解析の説明

    ・Patients who underwent treatment A had a significantly lower mortality than who underwent treatment B ( RR = 0.50; 95% CI = 0.35-0.65).

    ・ Patients aged 80 years or older were approximately two-fold more likely to die within 30 days of surgery compared with those in their 80s ( RR = 0.50; 95% CI = 0.35-0.65).