---
title: "医学論文を書くための心構え"
author: "坂本航太"
categories: [医学論文]
date-modified: "2025-10-13"
abstract-title: Abstract
abstract: ""
date: "2025-10-13"
---

## 目次

-   1.医学論文を書くための心構え

    -   論文執筆準備のための鉄則

        -   ①自分が論文を書く意義を見つめ直す。

        -   ②書かなければ、何も残らない。

        -   ③「書く」ことを意識して「読む」

        -   ④研究計画段階から論文を書き始める。

        -   ⑤論文執筆に要する時間の短縮を心掛ける。

-   2.Fool-proof Englishの表現技術

    -   Fool-proof Englishの鉄則

        -   ⑥Fool-proof Englishの表現技術を身に付ける。

        -   ⑦冗長・曖昧な表現を徹底的に排除する。

        -   ⑧動詞を制する者,作文を制する。

        -   ⑨論文に頻出する形容詞・副詞を押さえる。

        -   ⑩文と文のつなぎ方を意識する。

-   3.Introductionの書き方

    -   Introductionの鉄則

        -   ⑪Introductionは4パラグラフ構成を基本とする。

        -   ⑫各パラグラフに意識的にkey sentenceを挿入する。

        -   ⑬冗長な先行文献解説を排除する。

        -   ⑭末尾の研究目的に向かって、一直線に論理展開する。

-   4.Methodsの書き方

    -   Methodsの鉄則

        -   ⑮Methodsの再現可能性（reproductivity）を最重視する。

        -   ⑯デザイン、セッティング、適格基準、介入・曝露を明記する。

        -   ⑰アウトカムの定義と測定法を明記する。

        -   ⑱統計解析手法を完璧に記述する。

-   5.Resultsの書き方

    -   Resultsの鉄則

        -   ⑲Resultsには一切の価値判断を交えず、事実を客観的に淡々と書く。

        -   ⑳Methodsの順に沿って実験・観察結果を簡潔明瞭に書く。

        -   ㉑TableとFigureをself-explanatoryにする。

        -   ㉒Table・FIgureと本文の重複記載を避ける。

        -   ㉓Resultsにおける定型表現を用いたfool-proof Englishに徹する。

-   6.Discussionの書き方

    -   Discussionの鉄則

        -   ㉔Discussion全体を通じた論理一貫性を強く意識する。

        -   ㉕冗長・曖昧・蛇足を一切排除する。

        -   ㉖すべてのトピックをConclusionに向かって一直線につなげる。

        -   ㉗研究の新規性（novelty）を強調する。

        -   ㉘Resultsに基づいて議論する。言えないことは言わない。

        -   ㉙Spinは厳禁

        -   ㉚Limitationの記載をはしょってはならない

-   7.Abstractの書き方

    -   Abstractの鉄則

        -   ㉛「complete, accurate and clear」を追求する。

        -   ㉜キモとなる統計分析結果を厳選して示す。

        -   ㉝可能な限り、相対リスクだけでなく絶対リスクも示す。

        -   ㉞AbstractのConclusionに論文のすべてを凝縮する。

-   8\. Titleの書き方

    -   Titleの鉄則

        -   ㉟Titleには一期たりとも無駄なwordを含めてはならない。

        -   ㊱簡潔かつ必要十分な情報を含むtitleを書く。

        -   ㊲体言止めを旨とし、完全文タイトルを避ける。

-   9.投稿から掲載まで1

    -   投稿の鉄則

        -   ㊳投稿前に原稿の体裁を完璧にそろえる。

        -   ㊴Authorの要件を満たさない者をco-authorに加えるべきでない。

        -   ㊵Aims and Scopeに合う適切な投稿先を選択する。

        -   ㊶記念受験するべからず。身の程を知るべし。

-   10.投稿から掲載まで2

    -   Revisionの鉄則

        -   ㊷Rejectされても落ち込まない。

        -   ㊸Rejectに対するappealは時間の無駄と心得る。

        -   ㊹Revisionには初回投稿時より心血を注ぐ。

        -   ㊺Editor・Reviewerに敬意を払う。

        -   ㊻厳しい査読コメントにも耐えて修正する。

-   11.査読コメントの書き方

    -   査読の鉄則

        -   ㊼建設的、教育的、学術の発展に寄与するようなコメントを心掛ける。

        -   ㊽過度に批判的なコメント、攻撃的なコメントはご法度。

        -   ㊾Limitationを許容する。

        -   ㊿再査読の時点での新たな追加修正要求はご法度。

## 推薦の辞とはじめに

## 1.なぜ論文を書くのか？

これから医学研究にトライし論文を書きたいと考えている若手の医師や医学研究者の皆さんに、今一度、自らに問い直していただきたい。なぜ自分は研究し、論文を書くのか？学位をとるため？大学にいるから？周囲の同僚が研究しているから何となく自分も？自分の知的好奇心を満たすため？それらはいずれも研究を始める動機づけにはなりえても、それだけでは長く辛い研究を始める動機づけになりえても、それだけでは長く辛い研究と論文執筆のモチベーションを維持し続けることはできない。若手研究者の中には、研究に着手したはよいが一向に進展せず、当初の情熱がいつの間にかうすれてしまう者もいる。論文執筆が進まない状況が続いて憂鬱になり、しまいには途中で投げ出してしまうこともある。

モチベーションを維持するためには、「なぜ自分は論文を書くのか？」という問いに対する答えを自分なりに考え、到達可能なゴールを設定しなければならない。

臨床上のスキルアップや、それを基にした個々の患者への診療という人助けのプロセスは、臨床家にとっての自己実現の形である。論文を書くことは、それとは次元の異なる人助けのプロセスであり、もうひとつの自己実現であるといえよう。

**研究者は皆、究極的には、当該研究領域の発展に寄与することを目指して、研究し論文を執筆する。自分が書いた論文は、既存の医学知識をアップデートし、多くの臨床家に読まれ、彼らによって実践に移されることにより、多くの人命を救うことにつながるかもしれない。**

もちろん、たった1つの論文が世の中を変えるわけではない。医学の進歩は、古今東西の医学研究者たちが執筆した数多くの論文がもたらす成果の総和である。自分の論文もその中の1つである。ほんのわずかでもいい。医学の進歩のために、全力を尽くして、論文を書き上げよう。

**また、臨床家にとって、論文を書くことにはもうひとつ大きな意義がある。それは、自らの日常臨床を問い直し、より良い医療を実践するための大きな飛躍の一歩となりうることである。**

臨床研究の出発点はいつも、日常診療における経験である。臨床家が取り組むべき臨床研究のテーマは、日常臨床の現場に転がっている。現場で感じた素朴な疑問が、そのままクリニカル・クエスチョンになりうる。つまり、臨床研究は日常臨床の延長なのである。UpTo-Dateを眺めても、Pubmedで文献検索しても、自分のクリニカル・クエスチョンにこたえられるエビデンスは見つからないかもｓれない。新たなエビデンスを構築できるのは、自分だけかもしれない。

## 書かなければ何も残らない。

All the thinking , all the textual analysis , all the experiment and the data gathering are not anything until we write them up.

In the world of scholarship, we are what we write.

多くの研究者が文章を書くことの困難さを痛感している。しかし、ペーパーワークが終わらなければ、研究者の仕事は終わったことにならない。

No job is finished until the paperwork is done.

書くべきは、peer-reviewのあるjournalへの投稿論文、特に原著論文である。

原著論文とは、

1.  独創的な研究結果の最初の発表であり、

2.  実験や分析を再現でき、結果・結論の検証が可能な型式で書かれてあり、

3.  peer-review journalに刊行され、閲覧引用されるべき論文である。

学会発表だけで満足すべきではない。学会抄録にpeer-reviewはないこともあり、あったとしても論文ほど厳格でない。つまり、学会発表だけでは、研究成果は十分に評価されない。「書かなければ、何も残らない。」学会発表だけで論文化しないのは、研究者の貴重な時間の空費である。

## 英語で論文を書こう

誠に残念であるが、和文論文は、国際的な評価はほぼゼロである。

## 「書く」ことを意識して「読む」

論文を書くには、様々な準備が必要がある。その第一歩が、常日頃から英語論文を読むことである。**「忙しいから論文を読む暇がない」は禁句である。まともに論文を書ける医師は決してそんなセリフを吐かない。1日15分でもいいから論文を読む習慣は必要である。**

　論文を読むことは、ランニングと同じである。はじめは走ることが苦手でも、毎日走れば、そのうち苦になくなる。ただし、漠然と英語論文を読み続けても、英語論文を書けるようにはならない。AbstractとTableとFigureをConclusionだけ読めば論文の大筋はつかめる。しかし、そのような「ななめ読み」を続けては、臨床研究能力はいつまでたっても身に付かないし、英語論文を書くこともおぼつかない。

　自ら筆を執り英語論文を書くことを強く意識して、日ごろから論文を精読することが推奨される。10本の論文のabstractを読み飛ばすよりも、1本の論文を隅から隅まで精読する方が、臨床研究能力、論文執筆力向上にとって有用である。

IMRAD(Intoroduction,Methods,Results and Discussion）の順番に沿って、論理展開を追いながら読むことが、英語力・論理力だけでなく論文執筆力への近道である。

自分の専門分野における主要なjournalは毎号チェックしよう。さらに、pubmedで検索し、良い論文を厳選して読むようにしよう。ただし、検索そのものに時間をかけないことが肝心である。膨大な論文を検索しそれを整理することに時間と労力を費やし、検索した論文の精読を怠っている研究者が少なくない。限られた時間はなるべく論文を読むことに費やすべきである。

英語論文を精読する際、知らない単語を調べる必要が生じたら、英英辞典を使うことを推奨する。

日本人が医学英語論文を書くための効率的な方法として、自分の専門領域の論文に頻出する表現のリストを作成することをお勧めする。常日頃から英語論文を読んで、よく使われている表現、使える構文やパラグラフをリストアップしておこう。論文の各節（Introduction, Methods, Results , Discussion , Conclusion ,Acknowledgement）ごとに頻出表現をまとめておくとよい。

これによって、自分が使える英語表現のストックを増やしていくのである。自分で英語論文を書くとき、自作の頻出表現リストから、文中にふさわしい表現を当てはめて書くようにしよう

## いつ論文を書き始めるか？

論文を書き始める適切な時期は、研究の計画段階である。研究費の新生児、倫理委員会への申請時には研究のプロトコルを書く必要がある。臨床試験の場合は事前にプロトコルを作成し、登録しておく必要がある。その段階から、論文執筆を開始できる。

先行研究のレビューを完了させ、研究の背景・目的・方法をしっかり固めてから、データを取りにかからなければならない。

つまり、**データを収集する前の時点で論文を書き始められるはずである。**

【論文を書ける研究者の執筆パターン】

次々に論文を書き上げてしまう研究者は、データ収集を完了する前にIntoroduction、Methodsの執筆をほぼ完成させ、データが収集されたらすぐに解析して、Results、Discussionを一気に書き上げ、AbstractとTitoleもすぐに作成して、即座に投稿してしまう。

論文の各パーツを書く順番は、必然的に

**Introduction→Methods→Results→Discussion→Abstract→Titleの順となっている。**

【論文を書けない研究者の執筆パターン】

先行研究レビューも不十分なまま、研究仮説や研究デザイン、統計解析の方法を事前に固めることなしに、取れるデータをなんとなく取りにかかる。データを取りさえすれば、統計ソフトがなんとかしてくれると勘違いしてる。適当に集めたデータを無目的に統計ソフトにぶちこんで、「何か面白いことはないかな～」と仮説検定を繰り返す。

とりあえずMethodsから論文を書き始め、なんとなくResultsまで書き進む。Resultsの解釈をこじつけるために、何かそれらしい文献はないかと、あてどもない先行研究レビューを始める。そのうち、自分が出したResultsが、すでに先行研究で検証済みであることに気付き、Discussionの書きようがなくなる。

仕方がないので、再びデータをいじりはじめてP\<0.05を探す旅にでる。MethodsとResultsを書き直し、こじつけのストーリーに無理やりあてはめてIntroductionとDiscussionを書こうとするが、けっこく上手くいかない。挙句の宛にお蔵入りとなる。。

## 論文執筆時間の短縮

臨床医は忙しい。365日ずっと臨床に浸りきっていれば、論文を書くことは不可能だ。論文をを書きたければ、研究に専念できる時間を少しでも確保しなければならない。

ある勤務医は、勤め先の理解もあり、週に半日の「研究日」を確保できた。彼はその時間を利用して著者の研究室に通い詰め、年間1～2本は英文原著論文を書き続けている。彼の素晴らしい点は、「研究日」にch何と研究をやっていることである。

「論文を書く時間が足りない」と嘆く臨床家諸君は少なくない。時間が足りないならば、1本の論文を書き上げるトータルの時間そのものを短縮しよう。

効率的に論文を書くには、研究計画をしっかり立てることが肝心である。そうすればおのずと、統計解析や論文執筆の各ステップにおける時間短縮を実現できる。

研究を一緒に行える仲間を得ることも重要である。研究の各ステップにおいて、自分がやろうとしていること、やっていることが正しいかどうか、自身が持てないこともあるかもしれない。そうした場合、メンターや先輩・同僚に相談する。

もちろん、質の高い論文を書き上げることは、並大抵の努力では成し遂げられない。とはいえ、時間をかければより質が上がるとは限らない。早く書き上げ、早くアクセプトされないと、ときに苦杯をなさせることがある。書くべき論文のテーマを何年も温めていると、他の研究者に先を越されて論文を出版されてしまうのは、まああることである。