---
title: "情報幾何学入門"
author: "坂本航太"
categories: [数理統計]
date-modified: "2025-10-13"
abstract-title: Abstract
abstract: ""
date: "2025-10-13"
---

## 1回目

-   情報幾何学は、確率分布全体の集合を一つの空間（多様体）とみなし、そこに幾何学的な構造を与えて解析する学問分野である。

-   ユークリッド空間では、点と点の間に「距離」を定義したり、曲線の「長さ」を測ったりすることができる。情報幾何学は、この考え方を統計モデルの世界に持ち込みます。

    -   空間の「点」：一つ一つの確率分布

    -   空間の「座標」：分布を特徴づけるパラメータ

-   この「統計多様体」と呼ばれる空間に、距離や角度、曲率といった幾何学的な「ものさし」を導入することで、これまでとは異なる視点から統計モデルの性質を理解することを目指す。

-   スコア関数

    -   $S(\theta)=\frac{\partial log p(x;\theta)}{\partial \theta}$

-   スコア関数の性質

    -   $E[\frac{\partial log p(x;\theta)}{\partial \theta}] =0$

-   Fisher情報量

    -   $I_{ij}=E[\frac{\partial log p(x;\theta)}{\partial \theta_i}\frac{\partial log p(x;\theta)}{\partial \theta_j}]$

    -   スコア関数の分散共分散行列

-   定理

    -   確率変数Ｘがパラメータθによって定義される確率分布 $p(x;\theta)$ に従っているとする。変換Y=f(X)が逆関数$g=f^{-1}$ を持つとき、Xが持つフィッシャー情報量$I_x(\theta)$ とYが持つフィッシャー情報量

        $I_Y(\theta)$ は等しい。

-   Cramer-Raoの下限

    -   Cramer-Raoの下限は、不偏推定量が持ちうる分散の下限を与えます。

    -   パラメータθの任意の不偏推定量$\hat \theta$ の分散は次を満たす。

    -   $V[\hat \theta]≥\frac{1}{I(\theta)}$

    -   個の不等式は、Fisher情報量が大きいほど推定量の分散が小さくなる（＝より高精度な推定が可能になる）ことを示します。

-   Cramer-Raoの下限の幾何学的解釈

    -   $\hat \theta$ 不偏推定量→$E[\hat \theta \frac{\partial log p(x;\theta)}{\partial \theta} ] =1$

        これはそれぞれθとスコア関数をベクトルとみなすと、内積の期待値が1になることを意味している。

    -   これは正射影の話である。

    -   $\hat \theta-\theta$のベクトルをスコア関数の空間に射影しているときの長さの下限を示している。

## 3回目

-   リーマン計量

    -   リーマン多様体という「空間の捉え方」

    -   内積を考えるときは、グラム行列を通しておこう。

        -   座標を張るベクトルの大きさと内積＝グラム行列

    -