---
title: "潜在結果変数と統計的推測"
author: "坂本航太"
categories: [臨床試験]
date-modified: "2025-07-28"
abstract-title: Abstract
abstract: ""
date: "2025-07-28"
editor: visual
---

## 潜在結果変数と因果リスク差

対象者$i$にについて、観測されるアウトカムを0または1の値をとる2値変数$Y_i$で表す。また、関心のある試験治療とコントロール治療に対応する潜在結果変数を$Y_i{^0}$と$Y_i{^1}$と定義する。試験治療がアウトカムに与える因果効果は、両者に差があるかどうか、つまり以下で定義される。

$$
\tau_i = Y_i^1-Y_i^0
$$

この、 $\tau_iを$解析単位レベルの因果効果という。個人単位$i$で因果効果は推測不可能であるので、 $N$人からなる有限母集団を考え、統計的推測を行う。集団全体の潜在結果変数は以下の4パターンに分類できる。

$$
\begin{aligned}
・Y_i^0 =Y_i^1 = 0  \\
・Y_i^0 = 0 , Y_i^1 = 1  \\
・Y_i^0 =1, Y_i^1 = 0 \\
・Y_i^0 =Y_i^1 = 1
\end{aligned}
$$

これらのパターンの人数をそれぞれ、 $n_{00},n_{01},n_{10},n_{11}$ とすると、対象者全員に試験治療を用いたときとコントロール治療を用いたときの比較は、有限母集団因果リスク差（finite-population causal risk difference）として、以下で表せる。

$$
\bar \tau = \frac{\sum_{i=1}^N Y_i^1}{N}-\frac{\sum_{i=1}^N Y_i^0}{N} =\frac{n_{01}}{N}-\frac{n_{10}}{N}
$$

通常のリスク差と異なり、分母が対象者全員である。

また、有限母集団と無限母集団の違いにも注意する。無限母集団とは、 $N$人全員の潜在結果変数の組 $\{Y_i^0,Y_i^1 ; i = 1,...,N\}$からランダムサンプルとみなすことがある。そのときの $\tau_i$の期待値は、 $Pr(Y_i^0 =1) = \pi^0$と$Pr(Y_i^0 =1) = \pi^1$の差になる。このように定義された以下を母集団因果リスク差（super-population causal risk difference）または、（連続データでは）母集団平均因果効果（super-population average causal effect）という。

$$
\tau = E(Y_i^1-Y_i^0)=\pi^1-\pi^0
$$

別に因果リスク差だけでなく、因果リスク比、因果オッズ比と定義してもよい。

さらに、実際に試験に組み込まれた $N_1$人に注目して、その集団に試験治療を用いたときとコントロール治療を用いたときの因果リスク差を定義することができる。それはそれぞれ、治療群における有限母集団因果リスク差（finite-population causal risk difference for the treated)、治療群における母集団因果リスク差（super-population causal risk difference for the treated）と呼ぶ。

$$
\bar \tau^T= \frac{\sum_{i:A_i=1}Y_i^1}{N_1}-\frac{\sum_{i:A_i=1}Y_i^0}{N_1}
$$

$$
\tau^T = E(Y_i^1-Y_i^0 | A_i=1)
$$

## ランダム化の下での因果リスク差の推定

対象者$i$に試験治療を用いたかどうかを$A_i(A_i =1なら試験治療、A_i=0ならコントロール治療）$、アウトカムを $Y_i(Y_i=0ならイベントなし、Y_i=1ならイベントあり)$で表す。

Table 3-2 観測データの記法

+------------------------+---------------------+-----------------------------+---------------+
|                        | 試験治療( $A_1=1$ ) | コントロール治療( $A_1=0$ ) | 合計          |
+========================+=====================+=============================+===============+
| イベントなし( $Y_i=0$) | $N_1-S_1$           | $N_0-S_0$                   |               |
+------------------------+---------------------+-----------------------------+---------------+
| イベントなし( $Y_i=1$) | $S_1$               | $S_0$                       | $S$           |
+------------------------+---------------------+-----------------------------+---------------+
| 合計                   | $N_1$               | $_N0$                       | $N$           |
+------------------------+---------------------+-----------------------------+---------------+

Table 3-3 潜在結果変数の記法

+-----------------------------------------------+---------------------+-----------------------------+-------------+
|                                               | 試験治療( $A_1=1$ ) | コントロール治療( $A_1=0$ ) | 合計        |
+===============================================+=====================+=============================+=============+
| 常にイベントなし$(Y_i^0=Y_i^1=0)$             | $x_{00}$            | $n_{00}-x_{00}$             | $n_{00}$    |
+-----------------------------------------------+---------------------+-----------------------------+-------------+
| 試験治療のみイベントあり$(Y_i^0= 0 ,Y_i^1=1)$ | $x_{01}$            | $n_{01}-x_{01}$             | $n_{ 01}$   |
+-----------------------------------------------+---------------------+-----------------------------+-------------+
| コントロール治療のみイベントあり              | $x_{10}$            | $n_{10}-x_{10}$             |  $n_{10}$   |
|                                               |                     |                             |             |
| $(Y_i^0= 1 ,Y_i^1=0)$                         |                     |                             |             |
+-----------------------------------------------+---------------------+-----------------------------+-------------+
| 常にイベントあり                              | $x_{11}$            | $n_{11}-x_{11}$             |  $n_{11}$   |
|                                               |                     |                             |             |
| $(Y_i^0=Y_i^1=1)$                             |                     |                             |             |
+-----------------------------------------------+---------------------+-----------------------------+-------------+
| 合計                                          | $N_1$               | $N_0$                       | $N$         |
+-----------------------------------------------+---------------------+-----------------------------+-------------+

ここで、試験治療とコントロール治療がランダムに割り付けられていると仮定する。いわゆるリスク差は、以下となる。

$$
\hat \tau=\frac{S_1}{N_1} - \frac{S_0}{N_0} 
$$

また、潜在アウトカムの記法をTable3-3のように表す。この表はN組の $Y_i^0$と$Y_i^1$から構成される有限母集団のパターンを表している。つまり各パターンの人数 $n_{00},n_{01},n_{10},n_{11}$が分かれば、（ただし、総和がNであるという制約はある。）この有限母集団で因果効果が判断できる。一方で、ランダム割付をすることで、$x_{00},x_{01},x_{10},x_{11}$は確率変数とみなすことができる。

繰り返し、ランダム割付を行ってデータを発生させた仮想的な状況を考えてみる。ある個人がどちらの治療に割付られるかによって、$x_{00},x_{01},x_{10},x_{11}$はばらつく。観測データでいえば、割付結果によって、 $S_1=x_{01}+x_{10}$や $S_0=n_{10}-x_{10}+n_{11}-x_{11}$が確率的に変動する。ランダム化に基づく推測では、これらの確率的変動が因果リスク差を推定するときの誤差の源となる。

## 一致性、非干渉性、効果の一様性

対象者iと対象者jの2人がいて、この2つの比較 $Y_i-Y_j$が因果効果としてなんらかの意味を持つための条件を紹介する。

-   consistency

    -   consistencyとは、 $Y_i=(1-A_i)Y_i^0+A_iY_i^1$ で、観測されるデータと潜在結果変数の関係がリンクしていることをいう。

-   no interference between unit

    -   他の解析単位の治療が、別の解析単位に影響品という仮定

consistencyとno interference between unitを合わせて、SUTVA(Stable Unit Treatment Value Assumption）呼ばれることがある。consistencyとno interference between unitが成立していたとしても、 $Y_i-Y_j$という比較は、個人の因果効果（$\tau_i = Y_i-Y_jまたは\tau_j = Y_j-Y_i$）とは一致しない。

逆に、一致するための条件を考えると、 $Y_i^0=Y_j^0と\tau_j=\tau_i$ が成り立っていればよいと考えられる。1つめは対象者iと対象者jの疾患の状態に差がないことを意味する。これは交絡と関連付けて、比較可能性(comparability)という概念に相当する。また、2つ目は、解析単位間で因果効果が等しいことであり、これを効果の一様性（between-unit homogeneity of effects）と呼ぶ。これは、全ての解析個体i（i=1,...,N)において、 $Y_i^0とY_i^1$の相関が1ということを意味するから強い仮定である。

-   comparability

-   between-unit homogeneity of effects

## 条件付き因果リスク差

状況によっては、効果が均一とは考えにくく、しかも共変量によって効果の大きさや方向が変わるようなこともあり得る。このような共変量を効果修飾因子（effect modifier）という。潜在結果変数を用いて、 $\tau_i=Y_i^1-Y_i^0$と相関する因子を効果修飾因子といってもよい。効果修飾の有無は、共変量 $L_i$にによって、条件づけた因果リスク差を用いることができる。

$$
\tau(l) = E(Y_i^1-Y_i^0|L_i = l)
$$

$$
\bar \tau(l) =  \frac{\sum_{i:L_i=l}Y_i^1}{N_l}-\frac{\sum_{i:L_i=l}Y_i^0}{N_l}
$$

後者の有限母集団リスク差は、リスク差の分母 $N_l$は共変量が $L_i=l$である人数であることに注意。

そして、母集団因果リスク差と条件付き因果リスク差には、以下の関係がある。

$$
\tau = E(Y_i^1-Y_i^0)= \sum_l \tau(l) Pr(L_i=l) 
$$

$$
\bar \tau= \frac{1}{N}\sum_{i=1}^N \bar \tau(L_i)
$$

という関係がある。つまり、有限集団因果リスク差は、条件付きリスク差を対象者N人について、平均をしたものである。

## 割付メカニズム

対象者全体が、どの治療を受けるかを決める規則を、割付けメカニズム（assignment mechanism）という。個人ごとに一定の確率でランダムに割り付けるものである。このとき、割付確率は潜在結果変数 $\{Y_i^0,Y_i^1\}$と共変量$L_i$に依存しない。この単純ランダム化は以下のように表す。

$$
Pr(A_1,A_2,...,A_N | Y_i^0,Y_i^1,L_1,Y_2^0,Y_2^1,L_2,...,Y_N^0,Y_N^1,L_N)=\prod_{i=1}^N Pr(A_i)
$$

このとき、期待値の上では、割付けたグループ間で共変量の偏りは生じない。

Imbens and Rubinでは、無視可能（ignorable)と非交絡（uncounfounded）という概念を用いて分類している。

無視可能性とは、割付確率が観測データだけに依存することと定義され、以下のように表される。

$$
\begin{aligned}
Pr(A_1,A_2,...,A_N | Y_i^0,Y_i^1,L_1,Y_2^0,Y_2^1,L_2,...,Y_N^0,Y_N^1,L_N)\\
=Pr(A_1,A_2,...,A_N | Y_1,L_1,Y_2,L_2,...,Y_N,L_N)\\
\end{aligned}
$$ 非交絡とは、割付確率が共変量だけに依存することを指す。このよう簿は、強い無視可能性（strongly ignorable）とほぼ同じ意味で用いられている。強い無視可能な割付メカニズムは、割付が個人ごとに独立でなされるとき、以下で表すことをいう。

$$
Pr(A_1,A_2,...,A_N | Y_i^0,Y_i^1,L_1,Y_2^0,Y_2^1,L_2,...,Y_N^0,Y_N^1,L_N)=\prod_{i=1}^N Pr(A_i | L_i)
$$

なお、 $e(l)=Pr(A_i=1 | L_i = l)$をpropensity scoreという。

## 因果効果の識別に必要な2つの仮定

因果効果を識別するためには、割付メカニズムについて、2つの仮定が必要となる。第一の仮定は、