---
title: "臨床試験の中間事象"
author: "坂本航太"
categories: [臨床試験]
date-modified: "2025-07-28"
abstract-title: Abstract
abstract: ""
date: "2025-07-28"
editor: visual
---

## 臨床試験の中間事象

中間事象を扱う視点として、当該事象は治療の一部か、アウトカムの一部か、頻度は群間で異なるか、当該事象が生じた理由は何か、などが重要である。

## 中間事象とは？

ランダム化は、交絡に伴うバイアスを回避するための有力な手段であるが、ランダム化比較試験であってもあらゆる問題がないわけではない。たとえば、治療開始後に、以下のような事象が生じることがある。

-   対象者を選ぶための適格基準に違反することが、事後的に明らかになる。

-   プロトコールに規定された治療計画から逸脱する。例えば、治療の中止、治療の切り替え、代替え治療の開始

-   有害事象や死亡のため、アウトカムの一部が観測できなかったり、その解釈に影響を与えたりする。

これらの出来事を中間事象と呼ぶ。中間事象の取り扱いは、その試験でどのようなパラメータを推定しようとするかを左右するため、試験計画の段階で考慮すべきである。

## 中間事象は治療の一部か？アウトカムの一部か？

指針として、それが広い意味で治療の一部とみなされるのか、アウトカムの結果と解釈すべきかどうかは大事であろう。

例として、試験薬の投与中止が考えられる。もし、治療を開始する前に、試験への参加拒否を理由に、患者が投与中止を申し出たとしよう。このケースでは、偶発的なもので、解析結果への影響は軽微と判断して、解析対象集団から除外することが一般的である。

別の例として、なんらかの有害事象のため投与が中止され、有効性アウトカムが観測されなかったとしよう。このケースで、解析対象集団から除外すると、明らかに治験薬の安全性を過大推定してしまう。このケースでは、安全性解析対象集団には含めるべきだし、有効性の解釈においてこの患者が欠測のため解析に寄与しなかったとしても、そのことをきちんと報告すべきである。

中間事象の有無で層別して、試験治療群とコントロール群の結果を記述したり、比較したりすることがある。中間事象がアウトカムの一部ともなされるようなケースでは注意が必要である。なぜなら、治療の結果が良い層と悪い層を分けて、それぞれの層で試験治療とコントロール治療を比較してることになるからである。

## 中間事象の発現頻度が群間で異なるか

中間事象の発現頻度が群間で異なると、例えば、中間事象の発現頻度が少ない方が、その扱いによって因果効果の違いが生じにくい。一方で、中間事象が多く発現しており、しかもどちらかの群で偏っていると、因果効果への影響は大きくなるし、治療の有効性や安全性について解釈が難しくなる。

## 中間事象が生じた理由は何か、共変量によって説明できるか

中間事象によってアウトカムの欠測が生じ、それによって因果効果の推定にバイアスが含まれることがある。特にバイアスが懸念されるのは、中間事象が生じるメカニズムがアウトカムと関連しているときである。外的要因による欠測ならば、MCARの仮定の下で、欠測の影響を無視可能となるかもしれない。

**欠測に伴うバイアスを調整するには、欠測メカニズムを説明するような共変量を解析で考慮しなければならない。そのためには、どのような中間事象があり得るかを予想し、それが生じた理由など中間事象に関連するデータを収集できるように、あらかじめ計画を立てておく必要がある。**

## ICH E9 (R1)の5つのストラテジー

### 治療方針ストラテジー

対象者$i$の観察されるアウトカムを$Y_i$、ランダム割付の結果を$Z_i(Z_i = 1なら試験治療群、Z_i = 0 ならコントロール群$ として、ランダム化とアウトカムの途中に生じる中間事象を$M_i$で表すに。コントロール治療と試験治療のそれぞれの割付に対応するPotential Outcomeを$Y_i^{Z=0}$と$Y_i^{Z=1}$で表す。中間事象$M_i$の影響で、実際に行われる治療$A_i$ はランダム化の通りではないとする。あくまでランダム化の効果をみているのであって、$A_i$はみてない。

すなわち治療方針ストラテジーの推定目標は以下の、割付結果がアウトカムに与える平均因果効果と考えられる。

$$
E(Y_i^{Z=1} - Y_i^{Z=0})
$$

この推定目標の特徴は2つある。まず、この推定目標は、治療自体の効果というより、ランダム化時点で決めた治療方針のどちらが有効か、という意味での効果を表している。もう一つの特徴は、（治療変数）とは異なり、割付変数についてはランダム化により非交絡性が保証されている点である。そのため、治療方針ストラテジーを取れば、妥当な統計的推測が可能となる。

### 複合ストラテジー

試験治療とコントロール治療に対応する潜在的な中間事象の値を、それぞれ$M_i^{Z = 1}$ と$M_i^{Z = 0}$と表す。複合ストラテジーの推定目標は、アウトカムyと中間事象mのなんらかの関数$f(y,m)$ を用いて、以下のように表現できる。

$$
E[f(Y_i^{Z=1},M_i^{Z=1}) -  f(Y_i^{Z=0},M_i^{Z=0}) ]
$$

### 仮想ストラテジー

中間事象が発現しなかった仮想的な状況を想定する。この場合、関心のある推定目標は、仮想的な状況において得られたであろうアウトカムのある種の予測値である。

仮想ストラテジーでは、状況によって様々な推定目標が考えられる。ここでは、ランダムに割り付けられた治療を、対象者の一部が遵守しなかった状況を考えよう。そして、実際に受けた治療を、治療変数$A_i$ で表す。推定目標として自然なのは、治療変数$A_i$がアウトカム$Y_i$に与える因果効果である。試験治療とコントロール治療が仮に行われた状況に対応する潜在結果変数をそれぞれ、 $Y^{A=0}$、$Y^{A=1}$と表すと、$A_i$の平均因果効果は以下で表すことができる。

$$
E(Y_i^{A=1}-Y_i^{A=0})
$$

ただし、この場合の$A_i$は直接ランダムに割り付けられたものではないこと、治療を遵守しなかった対象者のアウトカムは医学的判断で採用できない可能性がある（欠測で扱いになる）ことに注意が必要である。この問題の対処法の1つとして、アウトカムになんらかのモデルを仮定して、結果を予測するというアプローチが考えられる。

### 主要層ストラテジー

省略

### 治療下ストラテジー

中間事象が発現し、治療が中止したり変更したりする時点より前の治療への反応をアウトカムとする。このストラテジーが特に意味を持つのは、経時データと生存時間データの場合であろう。アウトカムが経時的に繰り返し測定されている場合、全時点の測定値を採用するか、治療下のものに測定値を限定するかを選ばなければならない。同様に、特定のイベントまでの時間をアウトカムとして解析するとき、治療中止や変更を無視することもあれば、その時点で打ち切り（censoring）として取り扱うこともある。後者の解析では、**治療が継続している期間内のハザードを比較しており、治療下ストラテジーの一種と考えられる**

## 例：抗がん剤試験を想定するEstimand

アウトカムを生存時間とすると、3パターン感がられる。

| ストラテジー | 治療方針     | 治療下       | 仮想         |
|--------------|:-------------|--------------|--------------|
| 中間事象     | 治療切り替え | 治療切り替え | 治療切り替え |
| 考慮の仕方   | 無視         | 打ち切り     | IPCW         |
| 要約指標     | ハザード比   | ハザード比   | ハザード比   |