---
title: "冠詞について"
author: "坂本航太"
categories: [English]
date-modified: "2025-07-26"
abstract-title: Abstract
abstract: ""
date: "2025-07-26"
---

## 冠詞について

## 冠詞の基礎知識

-   可算名詞と不可算名詞

    -   可算名詞の分類

        -   普通名詞

            -   例：Patient

        -   集合名詞

            -   例：family

    -   不可算名詞

        -   物質名詞

            -   例：blood

        -   抽象名詞

            -   例：chemo-therapy

            -   概念を表すときは、不可算名詞になるが、個々の具体例を表す場合は可算名詞にもなりえる。

        -   固有名詞

            -   例：Japan

-   不定冠詞と定冠詞

    -   不定冠詞は**a\[an\]**は可算名詞につけられる。

    -   定冠詞**the**は、可算名詞と、不可算名詞のうち物質名詞・抽出名詞につけられる。

    -   固有名詞は、通常、無冠詞である。

可算名詞にも不可算名詞にもなる名詞がある。例えば、a stoneは「石」（可算名詞の普通名詞）であるが、無冠詞のstoneは「石材」（不可算名詞の物質名詞）となる。 a paperは「新聞」または「論文」（可算名詞の普通名詞）、無冠詞のpaperは「紙」（不可算名詞の物質名詞）となる。また、 a roomは「部屋」（可算名詞の普通名詞）、無冠詞のroomは「余地」（不可算名詞の抽象名詞）となる。

例： This house is made of stone. （stoneは無可算名詞の物質を表す）

例：A rolling stone gathers no moss （a stoneは可算名詞の普通名詞なので冠詞がいる）

## 不定冠詞と定冠詞

### 不定冠詞と定冠詞の基礎

可算名詞である場合、常に冠詞 or 定冠詞は必要であるが、名詞の前に以下がある場合は冠詞が省略される。

-   指示代名詞（this / that / these / those）

-   不定代名詞（some / any / each / another / either / no / neither )

-   人称代名詞の所有格（ my / our / your / his / her / its / their / whose）

しかし、原則として、不定冠詞**a\[an\]**は不特定の事柄、定冠詞**the**は、特定の事柄につけます。つまり、a\[an\]は、「たくさんのあるもののうちの一つ（one of many）」で、the は「唯一無二（one and only）」を示す。

原則として、初めて話題に上がる単数の可算名詞には、a\[an\]がついて、複数形の場合は、無冠詞となる。

The をつけるのは、以下のような場合である。

1.  同じものが再登場した場合

2.  その場の状況から初出であっても特定できる場合

3.  修飾語句がついて特定できる場合

4.  唯一無の存在

5.  必ずtheがつく単語の場合（the sameなど）

例：There is a clinic around the corner.

解説：clinicは初出なので、単数の可算名詞なので**a**をつけます。cornerは初出であっても、clinicの角は一意に定まるので（会話の中でも）one and onlyということで、theをつけています。なお、 a clinic is around the conerは文法的にOKですが使われません。注意しましょう。既にclinicも話題に上がっていれば、There is the clinic around the cornerが正しそうにめますが、これは言いません。その場合は、The clinic is around the corner.が正しい表現です。英語は難しいですね。

## 総称用法

不定冠詞の総称用法とは、不定冠詞を用いて不特定の個体を想定し、それを代表例として登場させ、その種が一般的にもつ特性を述べる用法です。「～というもの」となる。

例：A cat is a pet animal

訳：猫（というもの）は愛玩動物である。

ところが、主語ではA catでいいが、目的語では使いません。目的語の場合は catsとして、I like cats.が正しい表現である。

また、個体全体をイメージして論じる場合は、aではなく定冠詞theの総称用法を用います。

例：The chimpanzee is listed as dangered.

### 唯一無二のthe

地球や月は唯一無二のため、定冠詞をつけて、the earth、the moonとします。ただし、The をつけずに、University of Okayamaとしても文法上としては正しいです。なので、The をつけてもいいし、つけなくてもいい。難しいですね。

## 論文における冠詞

### 論文における可算名詞と不可算名詞の区別

1.  researchとstudy

どちらも「研究」という意味があります。researchは常に不可算名詞であるので、researchesのように複数形になることはありません。なので、 a researchのように不定冠詞をつけることも誤りになります。Studyは「勉強」、「学問」という意味では不可算名詞になりますが、「研究」という意味では可算名詞です。a studyは「1つの研究」、studiesは「複数の研究です」

例：Previous research showed that physical activity may be effective in reducing burnout.\
例：Numerous studies showed that treatment with hypertension can reduce the risk of cardiovascular disease.

### data,criteria,index

dataは、datnumという可算名詞の複数形です。なお、data-baseは可算名詞であり、a database、databasesが正しいです。

例：Data were collected from a large inpatient database.

criteriaはCriterionという可算名詞の複数形です。

例：The exclusion criteria were as follows: recent cardiopulmonary resuscitation; pregnancy.

### 抽象名詞の可算・不可算

以下の名詞は常に不可算となります。

-   evidence

-   information

-   knowledge

-   progress

-   advice

-   damage

-   harm

-   presence

-   absence

-   superiority

-   inferiority

-   smoking

-   severity

概念を表すときは不可算名詞、個々の具体例を示す場合には可算名詞になる抽象名詞は、論文ではかなり多く認められます。

例えば、recordは、「記録すること」を意味する場合は不可算名詞、「個々の具体的な記録」を表す場合は可算名詞（records）です。

例：Lipid profile was obtained from electronic medical records.

他にも、surgeryは通常不可算名詞で、「外科」を示します。しかし、「個々の手術や術式」を示す場合は可算名詞（a surgery, surgeries）となる。

例：Preserving elective surgeries was difficult in the Covid-19 pandemic.

以下の名詞も同様に、通常は不可算となるが、個々の具体例を示す場合は可算名詞になることもある。

-   disease、diagnosis、treatment

### 病名、症状、兆候、薬品名

「疾患・病気」を表すdisaease、illnessという単語は、

動詞の名詞系は通お嬢、不可算名詞です。例えば、initiation、recommendation、selection。しかし、一部は、概念を表す場合は不可算名詞となる。例えば、choice、investigation、onservation

-   疫学・統計用語の多くは可算名詞です。

    -   hypothesis

    -   mean

    -   standard deviation

    -   median

    -   rate

    -   proportion

    -   test

    -   odds ratio

-   不可算名詞もある

    -   effectiveness

    -   efficacy

    -   matching

## ネイティブチェックに引っかかった冠詞の例

康永先生は、大学で指導している研究者らが論文を執筆したときは、必ず、英文校正会社に原稿のネイティブチェックを依頼しているそうです。その例を示す。

例①

-   修正前：We applied self-controlled case series (SCCS) design to evaluate change in composite outcome of hospital admissions and emergency department visits.

-   修正後：We applied **a** self-controlled case series (SCCS) design to evaluate **changes** in **the** composite outcome of hospital admissions and emergency department visits.

ここで、design、change、outcomeはいずれも可算名詞であるので、aやtheをつける必要がある。designは初出の単数の可算名詞なのでaをつけている。changeは複数形にして、初出なので無冠詞とした。outdomeについては修飾語であるcompositeがついているので、特定できる、ということでtheをつけている。むず！！

例②

-   修正前：Baseline characteristics of eligible patients for SCCS are presented in Table1.

-   修正後：**The** baseline characteristics of eligible patients for the SCCS are presented in Table1.

ここで、CharacteristicsにはBaselineという修飾語がついているので、特定可能となるため**The**をつけている。SCCSについては、すでにMethodで説明しているので、特定可能なので**The**としている。

例③

-   修正前：All groups had significant decline in the composite outcome in subgroup analyses.

-   修正後：All groups had a significant decline in the composite outcome in the subgroup

declineについては、この場合は可算名詞なので、**a**をつけている。subgroup analyesesはMethodsで説明済なので、**the**をつけている。

例④

-   修正前：P value \< 0.05 was considered statistically significant.

-   修正後：A p value \< 0.05 was considered statistically significant.

valueは「価値」という抽象名詞で不可算になりますが、ここでは「数値」という意味で可算名詞になります。

例⑤

-   The patients backgrounds are shown in Table1.

論文の図表において、Table1, Figure1などは大文字で表記します。これらは本文中で初出であっても特定できます。Theをつけたくなりますが、慣習上、theをつける必要はありません。