---
title: "形容詞・副詞"
author: "坂本航太"
categories: [English]
date-modified: "2025-08-23"
abstract-title: Abstract
abstract: ""
date: "2025-08-23"
---

## 形容詞・副詞

形容詞は主に名詞を修飾し、副詞は主に動詞や形容詞を修飾することで、文章全体を豊かな内容にすることができます。本章では、最初に形容詞・副詞の基礎知識をおさらいします。

## 形容詞・副詞の基礎知識

### 形容詞の位置

### 数量形容詞

### 副詞の位置

### 比較級・最大級

## 論文における形容詞・副詞

### 論文では感情表現を用いない

論文では、以下のような感情表現を表す形容詞（およびその副詞形）を用いるべきではありません。

-   absolute,amazing,astonishing,astounding,...

書き手が勝手に抱いた感情に過ぎず、客観性を欠いているからです。特にResultにおいてこれらを用いるのは不適切です。Discussionでこれらの単語が使われているケースを少ないながら見受けられますが、決して推奨されません。

### 論文に頻出する形容詞・副詞

-   有意

    -   significant

-   正確、適切、妥当

    -   correct：正確な、（一般原則や基準に合致して）誤りがない

    -   Exact：正確な、（事実や真理に合致して）誤りがない

    -   accurate：正確な、（注意や努力が払われて）誤りがない

    -   precise：正確な、（細部に至るまで）精密な

    -   appropriate：（目的に合って）適当な、適切な

    -   adequate：（目的に）足りる、適切な

    -   Valid：妥当な、根拠の確実な

-   時期を表す形容詞

    -   past,previous,prior

    -   latest,recent

    -   current,present

-   それぞれ

-   とても重要

-   明らかでない

-   矛盾しない、一致する。

-   矛盾する、相反する、競争の的である。

-   同様の

-   同時に起こる

-   影響を受けやすい

-   より～しやすい、より～しにくい