---
title: "能動態と受動態"
author: "坂本航太"
categories: [English]
date-modified: "2025-08-08"
abstract-title: Abstract
abstract: ""
date: "2025-08-08"
---

## 能動態

論文では、**なるべく能動態を用いる方がよいでしょう。**なぜなら、一般的に能動態の方が少ない単語数で表現できるからである。本章ではまず、能動態と受動態の基礎を解説します。次に、能動態を原則とする、論文の文章の書き方を解説する。さらに、論文において受動態を用いてもよい場面、むしろ受動態を用いる方が望ましい場面を説明する。

## 受動態の基礎知識

## 受動態に変換できない文章

## 目的語がthat節の場合

## 句動詞を用いた文章の受動態

## 第4文型の受動態

## 論文における能動態と受動態

## 能動態を原則とする。

論文で能動態を用いると、主語にwe（単著の場合はI）という一人称名詞が使われることが多くなります。現代では、自然科学だけでなく社会科学の論文でも、一人称代名詞の使用が一般的に許容されています。能動態の文章は読みやすく、冗長になりにくいでしょう。また、文の主体が著者自身であることが分かり、論文における著者の見解や貢献をたやすく理解できます。

論文においてweが主語になる場合は以下の動詞がよく用いられます。

-   find, observe , identify , examine , investigate , verify , elucidate , clarify , hypothesize , use , perform , conduct ,analyze , evaluate , include ,exclude , categorize , divide , obtain , show , demonstrate , reveal , believe , consider , realize , assume , estimate , suggest , suppose , speculate

## 受動態を用いてもよい場合

## MethodおよびResults

実験・観察の方法や結果の記述において、実験者・観察者が著者ら（we ,the authors）であることは自明です。受動態にして、by usやby the authorsを省いてもよいでしょう。特に、能動態の文章の目的語がその文章の中心となる語句である場合、むしろ受動態に変換してその語句を文の先頭に配置した方がよいこともあります。

例：

-   This retrospective cohort study was conducted using a nationwide inpatient database in Japan.

-   Hospital volume was defined as the number of xxx per year in each hospital , and was categorized into quartiles.

-   The Cochran-Armitage trend test was used to evaluate the change in the proportion of patients undergoing early extubation over the study period.

-   This study was approved by the IRB .

実験者・観察者が著者らでweダルことが自明の場合でも、weを主語とする能動態で書いても問題はない。むしろ能動態にして、主語と動詞をなるべく文章の前に配置する方が望ましいです。

## 行為の主体が不明な場合

##