---
title: "冠詞について"
author: "坂本航太"
categories: [English]
date-modified: "2025-07-26"
abstract-title: Abstract
abstract: ""
date: "2025-07-26"
---

## 冠詞について

## 冠詞の基礎知識

-   可算名詞と不可算名詞

    -   可算名詞の分類

        -   普通名詞

            -   例：Patient

        -   集合名詞

            -   例：family

    -   不可算名詞

        -   物質名詞

            -   例：blood

        -   抽象名詞

            -   例：chemo-therapy

            -   概念を表すときは、不可算名詞になるが、個々の具体例を表す場合は可算名詞にもなりえる。

        -   固有名詞

            -   例：Japan

-   不定冠詞と定冠詞

    -   不定冠詞は**a\[an\]**は可算名詞につけられる。

    -   定冠詞**the**は、可算名詞と、不可算名詞のうち物質名詞・抽出名詞につけられる。

    -   固有名詞は、通常、無冠詞である。

可算名詞にも不可算名詞にもなる名詞がある。例えば、a stoneは「石」（可算名詞の普通名詞）であるが、無冠詞のstoneは「石材」（不可算名詞の物質名詞）となる。 a paperは「新聞」または「論文」（可算名詞の普通名詞）、無冠詞のpaperは「紙」（不可算名詞の物質名詞）となる。また、 a roomは「部屋」（可算名詞の普通名詞）、無冠詞のroomは「余地」（不可算名詞の抽象名詞）となる。

例： This house is made of stone. （stoneは無可算名詞の物質を表す）

例：A rolling stone gathers no moss （a stoneは可算名詞の普通名詞なので冠詞がいる）

## 不定冠詞と定冠詞

### 不定冠詞と定冠詞の基礎

可算名詞である場合、常に冠詞 or 定冠詞は必要であるが、名詞の前に以下がある場合は冠詞が省略される。

-   指示代名詞（this / that / these / those）

-   不定代名詞（some / any / each / another / either / no / neither )

-   人称代名詞の所有格（ my / our / your / his / her / its / their / whose）

しかし、原則として、不定冠詞**a\[an\]**は不特定の事柄、定冠詞**the**は、特定の事柄につけます。つまり、a\[an\]は、「たくさんのあるもののうちの一つ（one of many）」で、the は「唯一無二（one and only）」を示す。

原則として、初めて話題に上がる単数の可算名詞には、a\[an\]がついて、複数形の場合は、無冠詞となる。

The をつけるのは、以下のような場合である。

1.  同じものが再登場した場合

2.  その場の状況から初出であっても特定できる場合

3.  修飾語句がついて特定できる場合

4.  唯一無の存在

5.  必ずtheがつく単語の場合（the sameなど）

例：There is a clinic around the corner.

解説：clinicは初出なので、単数の可算名詞なので**a**をつけます。cornerは初出であっても、clinicの角は一意に定まるので（会話の中でも）one and onlyということで、theをつけています。なお、 a clinic is around the conerは文法的にOKですが使われません。注意しましょう。既にclinicも話題に上がっていれば、There is the clinic around the cornerが正しそうにめますが、これは言いません。その場合は、The clinic is around the corner.が正しい表現です。英語は難しいですね。

## 総称用法

不定冠詞の総称用法とは、不定冠詞を用いて不特定の個体を想定し、それを代表例として登場させ、その種が一般的にもつ特性を述べる用法です。「～というもの」となる。

例：A cat is a pet animal

訳：猫（というもの）は愛玩動物である。

ところが、主語ではA catでいいが、目的語では使いません。目的語の場合は catsとして、I like cats.が正しい表現である。

また、個体全体をイメージして論じる場合は、aではなく定冠詞theの総称用法を用います。

例：The chimpanzee is listed as dangered.

### 唯一無二のthe

地球や月は唯一無二のため、定冠詞をつけて、the earth、the moonとします。ただし、The をつけずに、University of Okayamaとしても文法上としては正しいです。なので、The をつけてもいいし、つけなくてもいい。難しいですね。

## 論文における冠詞

-   論文における可算名詞と不可算名詞の区別

1.  researchとstudy

どちらも「研究」という意味があります。researchは常に不可算名詞であるので、researchesのように複数形になることはありません。なので、 a researchのように不定冠詞をつけることも誤りになります。Studyは「勉強」、「学問」という意味では不可算名詞になりますが、「研究」という意味では可算名詞です。a studyは「1つの研究」、studiesは「複数の研究です」

例：